/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfazes;

import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Rectangle;
import java.sql.Connection;
import java.sql.DriverManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author VjJimmy
 */
public class FrmReportes extends javax.swing.JFrame {

    /**
     * Creates new form FrmReportes
     */
    public FrmReportes() {
        initComponents();
        centrarFrame();
       dtFecha.setVisible(false);
        
       
    }
    private void centrarFrame() {
        Dimension dim = this.getToolkit().getScreenSize();
        Rectangle rec = this.getBounds();
        this.setLocation((dim.width - rec.width) / 2, ((dim.height - rec.height) / 2) - 20);
        this.requestFocus();
    }
    void llenar_lista(){
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbbConsulta = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnGenerar = new javax.swing.JButton();
        dtFecha = new com.toedter.calendar.JMonthChooser();
        btnRetornar1 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbbConsulta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "RESERVACION", "EMPLEADOS", "AEROLINEAS", "HORARIOS DE SALIDA","VENTAS","CLIENTES" }));
        cbbConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbConsultaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Informes");

        jLabel2.setText("Tipo de Consulta ");

        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        btnRetornar1.setActionCommand("Retornar");
        btnRetornar1.setLabel("Retornar");
        btnRetornar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetornar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(cbbConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRetornar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbbConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnGenerar))
                    .addComponent(btnRetornar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        int seleccion = cbbConsulta.getSelectedIndex();
        System.out.println(seleccion);
        switch(seleccion)
        {
            case 0 :
                try {
                    dtFecha.setVisible(false);
              Connection cn;
               String path = "C:\\Users\\VjJimmy\\Desktop\\SistemaVentaPasajesAerolineas\\src\\Reportes\\reportereservacion.jasper";
        cn =DriverManager.getConnection("jdbc:postgresql://localhost:5432/SistemaVenta", "postgres", "Vjjimmy92");
        JasperReport reporte = null;
        reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint jp = JasperFillManager.fillReport(reporte, null,cn);
            JasperViewer view = new JasperViewer(jp);
            view.setTitle("Reporte Cliente");
            view.setExtendedState(Frame.MAXIMIZED_BOTH);
            view.setVisible(true);
        } catch (Exception e) {
        }
            break;
                case 1 :
                try {
              Connection cn;
               String path = "C:\\Users\\VjJimmy\\Desktop\\SistemaVentaPasajesAerolineas\\src\\Reportes\\Reporte_Empleados.jasper";
        cn =DriverManager.getConnection("jdbc:postgresql://localhost:5432/SistemaVenta", "postgres", "Vjjimmy92");
        JasperReport reporte = null;
        reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint jp = JasperFillManager.fillReport(reporte, null,cn);
            JasperViewer view = new JasperViewer(jp);
            view.setTitle("Reporte Empleados");
            view.setExtendedState(Frame.MAXIMIZED_BOTH);
            view.setVisible(true);
        } catch (Exception e) {
        }
            break;
                    case 2 :
                try {
              Connection cn;
               String path = "C:\\Users\\VjJimmy\\Desktop\\SistemaVentaPasajesAerolineas\\src\\Reportes\\Reporte_Aerolineas.jasper";
        cn =DriverManager.getConnection("jdbc:postgresql://localhost:5432/SistemaVenta", "postgres", "Vjjimmy92");
        JasperReport reporte = null;
        reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint jp = JasperFillManager.fillReport(reporte, null,cn);
            JasperViewer view = new JasperViewer(jp);
            view.setTitle("Reporte Reporte Aerolineas");
            view.setExtendedState(Frame.MAXIMIZED_BOTH);
            view.setVisible(true);
        } catch (Exception e) {
        }
            break;
                    case 3 :
                try {
              Connection cn;
               String path = "C:\\Users\\VjJimmy\\Desktop\\SistemaVentaPasajesAerolineas\\src\\Reportes\\ReporteHorarios.jasper";
        cn =DriverManager.getConnection("jdbc:postgresql://localhost:5432/SistemaVenta", "postgres", "Vjjimmy92");
        JasperReport reporte = null;
        reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint jp = JasperFillManager.fillReport(reporte, null,cn);
            JasperViewer view = new JasperViewer(jp);
            view.setTitle("Reporte horarios de salida");
            view.setExtendedState(Frame.MAXIMIZED_BOTH);
            view.setVisible(true);
        } catch (Exception e) {
        }
            break;
                    case 5:try {
                        Connection cn;
               String path = "C:\\Users\\VjJimmy\\Desktop\\SistemaVentaPasajesAerolineas\\src\\Reportes\\Reporte_Cliente.jasper";
        cn =DriverManager.getConnection("jdbc:postgresql://localhost:5432/SistemaVenta", "postgres", "Vjjimmy92");
        JasperReport reporte = null;
        reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint jp = JasperFillManager.fillReport(reporte, null,cn);
            JasperViewer view = new JasperViewer(jp);
            view.setTitle("Reporte horarios de salida");
            view.setExtendedState(Frame.MAXIMIZED_BOTH);
            view.setVisible(true);
                            
                        } catch (Exception e) {
                        }
                    break;
                             case 4 :
                                 if(dtFecha.getMonth() == 0){
                try {
              Connection cn;
               String path = "C:\\Users\\VjJimmy\\Desktop\\SistemaVentaPasajesAerolineas\\src\\Reportes\\ReporteVentaenero.jasper";
        cn =DriverManager.getConnection("jdbc:postgresql://localhost:5432/SistemaVenta", "postgres", "Vjjimmy92");
        JasperReport reporte = null;
        reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint jp = JasperFillManager.fillReport(reporte, null,cn);
            JasperViewer view = new JasperViewer(jp);
            view.setTitle("Reporte venta");
            view.setExtendedState(Frame.MAXIMIZED_BOTH);
            view.setVisible(true);
        } catch (Exception e) {
        }
                                 }
                  if(dtFecha.getMonth() == 1){
                try {
              Connection cn;
               String path = "C:\\Users\\VjJimmy\\Desktop\\SistemaVentaPasajesAerolineas\\src\\Reportes\\VentasFebrero.jasper";
        cn =DriverManager.getConnection("jdbc:postgresql://localhost:5432/SistemaVenta", "postgres", "Vjjimmy92");
        JasperReport reporte = null;
        reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint jp = JasperFillManager.fillReport(reporte, null,cn);
            JasperViewer view = new JasperViewer(jp);
            view.setTitle("Reporte Venta");
            view.setExtendedState(Frame.MAXIMIZED_BOTH);
            view.setVisible(true);
        } catch (Exception e) {
        }
             
             
                                 if(dtFecha.getMonth() == 6){
                try {
              Connection cn;
               String path = "C:\\Users\\VjJimmy\\Desktop\\SistemaVentaPasajesAerolineas\\src\\Reportes\\ReporteVentajulio.jasper";
        cn =DriverManager.getConnection("jdbc:postgresql://localhost:5432/SistemaVenta", "postgres", "Vjjimmy92");
        JasperReport reporte = null;
        reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint jp = JasperFillManager.fillReport(reporte, null,cn);
            JasperViewer view = new JasperViewer(jp);
            view.setTitle("Reporte Venta");
            view.setExtendedState(Frame.MAXIMIZED_BOTH);
            view.setVisible(true);
        } catch (Exception e) {
        }
             }
            break;
                        
        }        
    }//GEN-LAST:event_btnGenerarActionPerformed
    }
    private void cbbConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbConsultaActionPerformed
        if (cbbConsulta.getSelectedIndex() == 0) {
            dtFecha.setVisible(false);
            
        }
        if (cbbConsulta.getSelectedIndex() == 1) {
            dtFecha.setVisible(false);
        }
        if (cbbConsulta.getSelectedIndex() == 2) {
            dtFecha.setVisible(false);
        }
        if (cbbConsulta.getSelectedIndex() == 3) {
            dtFecha.setVisible(false);
        }
        if (cbbConsulta.getSelectedIndex() == 4) {
            dtFecha.setVisible(true);
        }
    }//GEN-LAST:event_cbbConsultaActionPerformed

    private void btnRetornar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetornar1ActionPerformed
        FormularioPrincipal retornno = new FormularioPrincipal();
        retornno.show();
        this.hide();
    }//GEN-LAST:event_btnRetornar1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmReportes().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private java.awt.Button btnRetornar1;
    private javax.swing.JComboBox cbbConsulta;
    private com.toedter.calendar.JMonthChooser dtFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
